# Generated by Django 5.2.7 on 2025-12-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_avatar_image_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('answer', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('question', 'profile')},
        ),
    ]
